DELETE FROM "WMHL7_TABLE_VALUES";	
DELETE FROM "WMHL7_CODE_TABLES";
DELETE FROM "WMHL7_PARTNERS" WHERE PARTNER_ID > 0;
UPDATE "WMHL7_TABLE_STATE" SET STATE=0;
DROP SEQUENCE "WMHL7_PARTNERS_SEQ";	
CREATE SEQUENCE WMHL7_PARTNERS_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;  
