CREATE TABLE "WMHL7_PARTNERS" (
    "PARTNER_ID"  INTEGER NOT NULL, 
    "PARTNER_PROFILE_ID" VARCHAR2(255) NOT NULL, 
     PRIMARY KEY("PARTNER_ID")
    );

CREATE TABLE "WMHL7_CODE_TABLES" (
	"PARTNER_ID"   INTEGER NOT NULL, 
	"TABLE_ID"   VARCHAR2(5) NOT NULL ,
	"TABLE_NAME" VARCHAR2(80), 
	"INHERIT" CHAR(1)  NOT NULL,
	"IS_ENABLED" CHAR(1)  NOT NULL,
	 PRIMARY KEY("PARTNER_ID","TABLE_ID"),
	 FOREIGN KEY ("PARTNER_ID") REFERENCES "WMHL7_PARTNERS" ("PARTNER_ID")
	);

CREATE TABLE "WMHL7_TABLE_VALUES" (	
	"PARTNER_ID" INTEGER NOT NULL,
	"CT_ID" VARCHAR2(5) NOT NULL, 
	"CT_VALUE" VARCHAR2(25) NOT NULL, 
	"DESCRIPTION" VARCHAR2(255), 
	 PRIMARY KEY ("PARTNER_ID", "CT_ID", "CT_VALUE"),
 	 FOREIGN KEY ("PARTNER_ID", "CT_ID")  REFERENCES "WMHL7_CODE_TABLES" ("PARTNER_ID", "TABLE_ID")
	);

CREATE TABLE "WMHL7_TABLE_STATE" (
    	"STATE" INTEGER NOT NULL
    	);


INSERT INTO WMHL7_PARTNERS(PARTNER_ID, PARTNER_PROFILE_ID) VALUES(0, '__WMHL7_DEFAULT_PROFILE__');

CREATE SEQUENCE WMHL7_PARTNERS_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;  

INSERT INTO WMHL7_TABLE_STATE(STATE) VALUES(0); 
    
CREATE TRIGGER WMHL7_PARTNERS_TRIGGER BEFORE INSERT ON WMHL7_PARTNERS FOR EACH ROW BEGIN SELECT WMHL7_PARTNERS_SEQ.NEXTVAL INTO :NEW.PARTNER_ID FROM DUAL;END;;
