DROP TABLE "WMHL7_TABLE_VALUES";
DROP TABLE "WMHL7_CODE_TABLES";
DROP TRIGGER "WMHL7_PARTNERS_TRIGGER";	
DROP SEQUENCE "WMHL7_PARTNERS_SEQ";	
DROP TABLE "WMHL7_PARTNERS";	
DROP TABLE "WMHL7_TABLE_STATE";