
CREATE TABLE IS_INFO (
	PRIMARYKEY			VARCHAR(24)		PRIMARY KEY,
	TAG				VARCHAR(24)		NOT NULL,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	IBAN_COUNTRY_CODE		CHAR(4)			NULL,
	IBAN_COUNTRY_CODE_POSITION	CHAR(4)			NULL,
	IBAN_COUNTRY_CODE_LENGTH	CHAR(4)			NULL,
	IBAN_CHECK_DIGITS_POSITION	CHAR(4)			NULL,
	IBAN_CHECK_DIGITS_LENGTH	CHAR(4)			NULL,
	BANK_IDENTIFIER_POSITION	CHAR(4)			NULL,
	BANK_IDENTIFIER_LENGTH		CHAR(4)			NULL,
	BRANCH_IDENTIFIER_POSITION	CHAR(4)			NULL,
	BRANCH_IDENTIFIER_LENGTH	CHAR(4)			NULL,
	IBAN_NATIONAL_ID_LENGTH		CHAR(4)			NULL,
	ACCOUNT_NUMBER_POSITION   CHAR(4)			NOT	NULL,
	ACCOUNT_NUMBER_LENGTH CHAR(4)			NOT	NULL,
	IBAN_TOTAL_LENGTH CHAR(4)			NOT	NULL,
	SEPA CHAR(2)			NOT	NULL,
	OPTIONAL_COMMENCE_DATE VARCHAR(12)		NULL,
	MANDATORY_COMMENCE_DATE VARCHAR(12)		NULL
);	


CREATE  INDEX IDX_BI_CODE ON IS_INFO (IBAN_COUNTRY_CODE	ASC);

