CREATE TABLE IBAN_PLUS (
	PRIMARYKEY			VARCHAR(35)		NOT NULL,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	RECORD_KEY 			VARCHAR(30)  		NOT NULL,
	INSTITUTION_NAME 			VARCHAR(155)	  	NOT NULL,
	COUNTRY_NAME 				VARCHAR(90) 	 	NOT NULL,
	ISO_COUNTRY_CODE 			CHAR(2)  	 	NOT NULL,	
  IBAN_ISO_COUNTRY_CODE 	CHAR(2)  	NOT NULL,	
  IBAN_BIC VARCHAR(11) 	 	NOT NULL,
  ROUTING_BIC VARCHAR(11) 	 	NOT NULL,
	IBAN_NATIONAL_ID 			VARCHAR(45) 	 	NOT NULL,	
	SERVICE_CONTEXT 		VARCHAR(10),	
	FIELD_A 		CHAR(35),	
	FIELD_B 		VARCHAR(70)
	) ;


ALTER TABLE IBAN_PLUS ADD CONSTRAINT PK_SR_IBANPlus PRIMARY KEY (PRIMARYKEY);

CREATE  INDEX IDX_IBANPlus_INST ON IBAN_PLUS(INSTITUTION_NAME ASC) ;

CREATE  INDEX IDX_IBANPlus_COUNTRYNAME ON IBAN_PLUS(COUNTRY_NAME  ASC);

CREATE  INDEX IDX_IBANPlus_MODFLAG ON IBAN_PLUS(MODFLAG  ASC);

