
CREATE TABLE SSIPlus (
	PRIMARY_KEY			VARCHAR(24)		PRIMARY KEY,
	MOD_FLAG 			CHAR(2)  		NOT NULL,		
	RECORD_KEY 		    VARCHAR(20)  	NOT NULL,		
	GROUP_KEY 		    VARCHAR(20)  	NOT NULL,	
	ASSET_CATEGORY 		VARCHAR(4)  	NOT NULL,
	OWNER_KEY 			VARCHAR(20)     NOT NULL,
	OWNER_BIC 			VARCHAR(11),
	ISO_CURRENCY_CODE 	VARCHAR(10),
	CORRESPONDENT_BIC	VARCHAR(15),
	ACCOUNT_NUMBER		VARCHAR(85),		
	PREFERRED			VARCHAR(2),
	INTERMEDIARY_1_BIC	VARCHAR(12),
	INTERMEDIARY_1_AC_NUMBER			VARCHAR(85),
	INTERMEDIARY_2_BIC	VARCHAR(12),
	INTERMEDIARY_2_AC_NUMBER	VARCHAR(85),
	INSTITUTION_NAME	VARCHAR(110),
	CITY				VARCHAR(70),
	CPS					VARCHAR(90),
	COUNTRY_NAME		VARCHAR(70),
	ISO_COUNTRY_CODE	VARCHAR(4),
	START_DATE			VARCHAR(10),
	STOP_DATE			VARCHAR(8),		
	FIELD_A				VARCHAR(70),
	FIELD_B	 			VARCHAR(70)
);


CREATE  INDEX IDX_SSI_MODFLAG ON SSIPlus (MOD_FLAG	ASC);

CREATE  INDEX IDX_SSI_BIC ON SSIPlus (OWNER_BIC	ASC);

CREATE  INDEX IDX_SSI_CITY ON SSIPlus (CITY	ASC);

CREATE  INDEX IDX_SSI_COUNTRY_CODE ON SSIPlus (ISO_COUNTRY_CODE	ASC);
