
CREATE TABLE IS_INFO (
	PRIMARYKEY			VARCHAR(24)		NOT NULL,
	TAG				VARCHAR(24)		NOT NULL,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	IBAN_COUNTRY_CODE		CHAR(4),
	IBAN_COUNTRY_CODE_POSITION	CHAR(4),
	IBAN_COUNTRY_CODE_LENGTH	CHAR(4),
	IBAN_CHECK_DIGITS_POSITION	CHAR(4),
	IBAN_CHECK_DIGITS_LENGTH	CHAR(4),
	BANK_IDENTIFIER_POSITION	CHAR(4),
	BANK_IDENTIFIER_LENGTH		CHAR(4),
	BRANCH_IDENTIFIER_POSITION	CHAR(4),
	BRANCH_IDENTIFIER_LENGTH	CHAR(4),
	IBAN_NATIONAL_ID_LENGTH		CHAR(4),
	ACCOUNT_NUMBER_POSITION   CHAR(4)			NOT	NULL,
	ACCOUNT_NUMBER_LENGTH CHAR(4)			NOT	NULL,
	IBAN_TOTAL_LENGTH CHAR(4)			NOT	NULL,
	SEPA CHAR(2)			NOT	NULL,
	OPTIONAL_COMMENCE_DATE VARCHAR(12),
	MANDATORY_COMMENCE_DATE VARCHAR(12)		
);


ALTER TABLE IS_INFO ADD CONSTRAINT PK_BI_BIC PRIMARY KEY (PRIMARYKEY);


CREATE  INDEX IDX_IS_CODE ON IS_INFO (MODFLAG	ASC);













