CREATE TABLE IBAN_PLUS (
	PRIMARYKEY			VARCHAR(35)		PRIMARY KEY,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	RECORD_KEY 			VARCHAR(30)  		NOT NULL,
	INSTITUTION_NAME 			VARCHAR(155)	  	NOT NULL,
	COUNTRY_NAME 				VARCHAR(90) 	 	NOT NULL,
	ISO_COUNTRY_CODE 			CHAR(2)  	 	NOT NULL,	
	IBAN_ISO_COUNTRY_CODE 	CHAR(2)  	NOT NULL,	
	IBAN_BIC VARCHAR(11) 	 	NOT NULL,
	ROUTING_BIC VARCHAR(11) 	 	NOT NULL,
	IBAN_NATIONAL_ID 			VARCHAR(45) 	 	NOT NULL,	
	SERVICE_CONTEXT 		VARCHAR(10) NULL,	
	FIELD_A 		CHAR(35)  NULL,	
	FIELD_B 		VARCHAR(70)  NULL
);


CREATE  INDEX IDX_IBANPlus_BIC ON IBAN_PLUS(IBAN_BIC); 

CREATE  INDEX IDX_IBANPlus_INST ON IBAN_PLUS(INSTITUTION_NAME); 

CREATE  INDEX IDX_IBANPlus_COUNTRYNAME ON IBAN_PLUS(COUNTRY_NAME) ;

CREATE  INDEX IDX_IBANPlus_MODFLAG ON IBAN_PLUS(MODFLAG) ;
