
CREATE TABLE SR_INFO (
	PRIMARYKEY			VARCHAR(24)		NOT NULL,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	RECORD_KEY 			VARCHAR(24),			
	BIC 			VARCHAR(24),			
	INSTITUTION_NAME 		VARCHAR(135),
	CITY 			VARCHAR(45),
	COUNTRY_CODE 			CHAR(2),
	SCHEME 		VARCHAR(45),
	ADHERENT_BIC 	VARCHAR(20),
	ADHERENCE_START_DATE 	VARCHAR(24),
	ADHERENCE_STOP_DATE 	VARCHAR(24),
	PAYMENT_CHANNEL_ID 		VARCHAR(24),
	PREFERRED_CHANNEL_FLAG 		CHAR(2),
	REACHABILITY 		CHAR(2),
	INTERMEDIARY_INSTITUTION_BIC 	VARCHAR(24),
	START_DATE 			VARCHAR(24),
	STOP_DATE 			VARCHAR(24),
	AOS 				VARCHAR(10),
	FIELD_A				VARCHAR(50),
	FIELD_B				VARCHAR(90)
) ;


ALTER TABLE SR_INFO ADD CONSTRAINT PK_SR PRIMARY KEY (PRIMARYKEY);

CREATE  INDEX IDX_SR_MODFLAG ON SR_INFO (MODFLAG	ASC);

CREATE  INDEX IDX_SR_BIC_CODE ON SR_INFO (BIC	ASC);

CREATE  INDEX IDX_SR_CITY_HEADING ON SR_INFO (CITY	ASC);

CREATE  INDEX IDX_SR_COUNTRY_CODE ON SR_INFO (COUNTRY_CODE	ASC);



