CREATE TABLE BIC (
	PRIMARYKEY			VARCHAR(24)		NOT NULL,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	INSTITUTION 		VARCHAR(105)  	NOT NULL,	
	CITY 				VARCHAR(35)  	NOT NULL,
	CODE 				VARCHAR(11),
	BRANCH 				VARCHAR(70),	
	SUBTYPE 			VARCHAR(4),
	VALUEADDEDSERVICES 	VARCHAR(60),
	EXTRAINFORMATION	VARCHAR(35),	
	PHYSICALADDRESS 	VARCHAR(140),
	ZIPCODE				VARCHAR(15),
	LOCATION 			VARCHAR(105),
	COUNTRYNAME 		VARCHAR(70),
	POBNUMBER			VARCHAR(35),
	POBZIPCODE			VARCHAR(15),
	POBLOCATION 		VARCHAR(105),
	POBCOUNTRYNAME 		VARCHAR(70),
	SOURCEOFINFORMATION	VARCHAR(2),
	SPECIALCODE			VARCHAR(6),		
	UPDATEDATE			VARCHAR(6),
	ORIGINOFKEY			VARCHAR(4),
	BICKEY				VARCHAR(8),
	CHECKDIGIT			VARCHAR(2),
	CHIPSUID			VARCHAR(6),
	NATIONALID			VARCHAR(15),
	ACTIVATIONDATE		VARCHAR(6),		
	DEACTIVATIONDATE	VARCHAR(6),
	UMCHIPSUID			VARCHAR(8),
	UMNATIONALID		VARCHAR(8),
	NEWBICKEY			VARCHAR(8),
	COMMITFLAG			VARCHAR(1),
	COMMITINST			VARCHAR(1),
	USERFIELD			VARCHAR(128),
	CBINFO				VARCHAR(68),		
	CBINFODATES			VARCHAR(58),
	MERGEFLAG			VARCHAR(1),
	MERGEMETHOD			VARCHAR(1),
	MERGERESULT			VARCHAR(1),
	TRAILER				VARCHAR(56)
) ;

ALTER TABLE BIC ADD CONSTRAINT PK_BIC PRIMARY KEY (PRIMARYKEY);

CREATE  INDEX IDX_CODE ON BIC (CODE ASC);

CREATE  INDEX IDX_BICKEY ON BIC (BICKEY	ASC);

CREATE  INDEX IDX_INST ON BIC(INSTITUTION ASC) ;

CREATE  INDEX IDX_CITY ON BIC(CITY ASC);

CREATE  INDEX IDX_BRANCH ON BIC(BRANCH  ASC);

CREATE  INDEX IDX_LOCATION ON BIC(LOCATION  ASC);

CREATE  INDEX IDX_COUNTRYNAME ON BIC(COUNTRYNAME  ASC);

CREATE  INDEX IDX_MODFLAG ON BIC(MODFLAG  ASC);



