

CREATE TABLE SR_INFO (
	PRIMARYKEY			VARCHAR(24)		PRIMARY KEY,
	MODFLAG 			CHAR(1)  		NOT NULL,			
	RECORD_KEY 			VARCHAR(24) NULL,			
	BIC 			VARCHAR(24) NULL,			
	INSTITUTION_NAME 		VARCHAR(135) NULL,
	CITY 			VARCHAR(45) NULL,
	COUNTRY_CODE 			CHAR(2) NULL,
	SCHEME 		VARCHAR(45) NULL,
	ADHERENT_BIC 	VARCHAR(20) NULL,
	ADHERENCE_START_DATE 	VARCHAR(24) NULL,
	ADHERENCE_STOP_DATE 	VARCHAR(24) NULL,
	PAYMENT_CHANNEL_ID 		VARCHAR(24) NULL,
	PREFERRED_CHANNEL_FLAG 		CHAR(2) NULL,
	REACHABILITY 		CHAR(2) NULL,
	INTERMEDIARY_INSTITUTION_BIC 	VARCHAR(24) NULL,
	START_DATE 			VARCHAR(24) NULL,
	STOP_DATE 			VARCHAR(24) NULL,
	AOS 				VARCHAR(10) NULL,
	FIELD_A				VARCHAR(50) NULL,
	FIELD_B				VARCHAR(90) NULL
);


CREATE  INDEX IDX_SR_MODFLAG ON SR_INFO (MODFLAG	ASC);

CREATE  INDEX IDX_SR_BIC_CODE ON SR_INFO (BIC	ASC);

CREATE  INDEX IDX_SR_CITY_HEADING ON SR_INFO (CITY	ASC);

CREATE  INDEX IDX_SR_COUNTRY_CODE ON SR_INFO (COUNTRY_CODE	ASC);





