<?xml version="1.0" encoding="UTF-8"?>
<Doc:Document xmlns:Doc="urn:swift:xsd:service.name$camt.005.002.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Doc:camt.005.002.01>
		<Doc:MsgId>
			<Doc:Id>ABCDEFGHIJKLMNOPQRST123456789012345</Doc:Id>
		</Doc:MsgId>
		<Doc:TxQryDef>
			<Doc:QryTp>ALLL</Doc:QryTp>
			<Doc:TxCrit>
				<Doc:QryNm>ABCDEFGHIJKLMNOPQRST123456789012345</Doc:QryNm>
			</Doc:TxCrit>
		</Doc:TxQryDef>
	</Doc:camt.005.002.01>
</Doc:Document>
