CREATE TABLE [WMHL7_PARTNERS]  (
    [PARTNER_ID]    INTEGER NOT NULL IDENTITY(0,1), 
    [PARTNER_PROFILE_ID]  VARCHAR(255) NOT NULL, 
     PRIMARY KEY([PARTNER_ID])
    );

CREATE TABLE [WMHL7_CODE_TABLES] (
	[PARTNER_ID] INTEGER NOT NULL, 
	[TABLE_ID]   VARCHAR(5) NOT NULL,
	[TABLE_NAME] VARCHAR(80), 
	[INHERIT] CHAR(1)  NOT NULL,
	[IS_ENABLED] CHAR(1) NOT NULL,
	 PRIMARY KEY([PARTNER_ID],[TABLE_ID]),
	 FOREIGN KEY ([PARTNER_ID]) REFERENCES [WMHL7_PARTNERS] ([PARTNER_ID])
	);

CREATE TABLE [WMHL7_TABLE_VALUES] (	
	[PARTNER_ID] INTEGER NOT NULL,
	[CT_ID] VARCHAR(5) NOT NULL, 
	[CT_VALUE] VARCHAR(25) NOT NULL, 
	[DESCRIPTION] VARCHAR(255), 
	 PRIMARY KEY ([PARTNER_ID], [CT_ID], [CT_VALUE]),
 	 FOREIGN KEY ([PARTNER_ID], [CT_ID] )  REFERENCES [WMHL7_CODE_TABLES] ([PARTNER_ID], [TABLE_ID])
	);

        
    
    
CREATE TABLE [WMHL7_TABLE_STATE]  (
    [STATE]  INTEGER NOT NULL
    );	
    
INSERT INTO WMHL7_TABLE_STATE(STATE) VALUES(0);   
INSERT INTO WMHL7_PARTNERS(PARTNER_PROFILE_ID) VALUES('__WMHL7_DEFAULT_PROFILE__');
