<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createContentID</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required nodeID</value>
    <value>[i] field:0:required friendlyName</value>
    <value>[i] object:0:required metadataMap</value>
    <value>[o] field:0:required contentID</value>
    <value>[o] field:0:required status</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpTdHJpbmcgbm9kZUlE
ID0gSURhdGFVdGlsLmdldFN0cmluZyhjdXJzb3IsICJub2RlSUQiKTsNClN0cmluZyByZXBvTmFt
ZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3Vyc29yLCAiZnJpZW5kbHlOYW1lIik7DQpPYmplY3Qg
bWV0YWRhdGFNYXAgPSBJRGF0YVV0aWwuZ2V0KGN1cnNvciwgIm1ldGFkYXRhTWFwIik7DQpjdXJz
b3IuZGVzdHJveSgpOw0KU3RyaW5nIHN0YXR1cyA9ICIiOw0KU3RyaW5nIGNvbnRlbnRJRCA9IG51
bGw7DQpFQ29udGVudFJlcG9zaXRvcnkgcmVwbyA9IHV0aWwuZ2V0UmVwbyhyZXBvTmFtZSk7DQpp
ZiAobWV0YWRhdGFNYXAgaW5zdGFuY2VvZiBTdHJpbmcpIHsNCglTdHJpbmcgc3RyaW5nTWFwID0g
KFN0cmluZykgbWV0YWRhdGFNYXA7DQoJbWV0YWRhdGFNYXAgPSBuZXcgSGFzaE1hcDxTdHJpbmcs
IFN0cmluZz4oKTsNCglzdHJpbmdNYXAgPSBzdHJpbmdNYXAucmVwbGFjZUFsbCgifSIsICIiKTsN
CglTdHJpbmdbXSBtYXBWYWx1ZXMgPSBzdHJpbmdNYXAuc3BsaXQoIiwiKTsNCglmb3IgKFN0cmlu
ZyB2YWx1ZVBhaXIgOiBtYXBWYWx1ZXMpIHsNCgkJdmFsdWVQYWlyID0gdmFsdWVQYWlyLnN1YnN0
cmluZygxKTsNCgkJU3lzdGVtLm91dC5wcmludGxuKHZhbHVlUGFpcik7DQoJCVN0cmluZ1tdIGtl
eVBhaXIgPSB2YWx1ZVBhaXIuc3BsaXQoIj0iKTsNCgkJU3RyaW5nIGtleSA9IGtleVBhaXJbMF07
DQoJCVN0cmluZyB2YWx1ZSA9IGtleVBhaXJbMV07DQoJCSgoSGFzaE1hcDxTdHJpbmcsIFN0cmlu
Zz4pIG1ldGFkYXRhTWFwKS5wdXQoa2V5LCB2YWx1ZSk7DQoJfQ0KfQ0KDQppZiAocmVwbyA9PSBu
dWxsKSB7DQoJc3RhdHVzID0gIkZhaWxlZDogUmVwb3NpdG9yeSAoIiArIHJlcG9OYW1lDQoJCQkr
ICIpIG5vdCBjb25maWd1cmVkLCBwbGVhc2UgZmlyc3QgcnVuIGFkZENvbm5lY3Rpb24uIjsNCn0g
ZWxzZSB7DQoJdHJ5IHsNCgkJaWYgKCFyZXBvLmlzTGl2ZSgpKSB7DQoJCQlyZXBvLmdldFJlcG8o
KTsNCgkJfQ0KCQljb250ZW50SUQgPSByZXBvLmdldE5ld0NvbnRlbnRJRCgpOw0KCQlpbnRbXSBu
b2RlSURzID0geyBJbnRlZ2VyLnZhbHVlT2Yobm9kZUlEKSB9Ow0KCQlTdHJpbmdbXSBmaWxlTmFt
ZXMgPSB7ICIiIH07DQoJCXJlcG8uc3RvcmVDb250ZW50KGNvbnRlbnRJRCwgbm9kZUlEcywgZmls
ZU5hbWVzLCB0cnVlKTsNCgkJaWYgKG1ldGFkYXRhTWFwICE9IG51bGwpIHsNCgkJCXJlcG8uYWRk
TWV0YWRhdGEoY29udGVudElELA0KCQkJCQkoSGFzaE1hcDxTdHJpbmcsIFN0cmluZz4pIG1ldGFk
YXRhTWFwKTsNCgkJfQ0KCQlzdGF0dXMgPSAiU3VjY2Vzc2Z1bDogQ29udGVudElEIGNyZWF0ZWQg
IiArIGNvbnRlbnRJRA0KCQkJCSsgIiBpbiBub2RlKCIgKyBub2RlSUQgKyAiKS4iOw0KCX0gY2F0
Y2ggKEV4Y2VwdGlvbiBlKSB7DQoJCVN0cmluZ1dyaXRlciByZXN1bHQgPSBuZXcgU3RyaW5nV3Jp
dGVyKCk7DQoJCVByaW50V3JpdGVyIHByaW50V3JpdGVyID0gbmV3IFByaW50V3JpdGVyKHJlc3Vs
dCk7DQoJCWUucHJpbnRTdGFja1RyYWNlKHByaW50V3JpdGVyKTsNCgkJdXRpbC5sb2dnZXIuZXJy
b3IocmVzdWx0LnRvU3RyaW5nKCkpOw0KCQllLnByaW50U3RhY2tUcmFjZSgpOw0KCQlzdGF0dXMg
PSAiRmFpbGVkOiBVbmFibGUgdG8gY3JlYXRlIG5ldyBDb250ZW50SUQuIjsNCgl9DQp9DQpjdXJz
b3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoY3Vyc29yLCAic3RhdHVz
Iiwgc3RhdHVzKTsNCklEYXRhVXRpbC5wdXQoY3Vyc29yLCAiY29udGVudElEIiwgY29udGVudElE
KTsNCmN1cnNvci5kZXN0cm95KCk7DQo=</value>
</Values>
