<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createFilter</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required friendlyName</value>
    <value>[i] field:0:required cspFilterFriendlyName</value>
    <value>[i] field:0:required nodeIDs</value>
    <value>[i] field:0:required contentDefinition</value>
    <value>[i] field:0:optional description</value>
    <value>[o] field:0:required status</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsNCglpZiAocGlwZWxpbmUgIT0gbnVsbCkgew0KCQlJRGF0YUN1cnNvciBwaXBlQ3Vyc29y
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJCXRyeSB7DQoJCQlTdHJpbmcgc3RhdHVzID0gIlN1
Y2Nlc3MiOw0KCQkJU3RyaW5nIGNzcEZyaWVuZGx5TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmco
cGlwZUN1cnNvciwNCgkJCQkJImZyaWVuZGx5TmFtZSIpOw0KCQkJT2JqZWN0IG5vZGVJRHMgPSBJ
RGF0YVV0aWwuZ2V0KHBpcGVDdXJzb3IsICJub2RlSURzIik7DQoJCQlPYmplY3QgY29udGVudERl
ZnMgPSBJRGF0YVV0aWwuZ2V0KHBpcGVDdXJzb3IsDQoJCQkJCSJjb250ZW50RGVmaW5pdGlvbiIp
Ow0KCQkJT2JqZWN0IGRlc2NyaXB0aW9uID0gSURhdGFVdGlsLmdldChwaXBlQ3Vyc29yLA0KCQkJ
CQkiZGVzY3JpcHRpb24iKTsNCgkJCUVDb250ZW50UmVwb3NpdG9yeSByZXBvID0gdXRpbC5nZXRS
ZXBvKGNzcEZyaWVuZGx5TmFtZSk7DQoJCQlpZiAocmVwbyAhPSBudWxsICYmIG5vZGVJRHMgIT0g
bnVsbCkgew0KCQkJCWlmICghcmVwby5pc0xpdmUoKSkgew0KCQkJCQlyZXBvLmdldFJlcG8oKTsN
CgkJCQl9DQoJCQkJSURhdGFVdGlsLnB1dChwaXBlQ3Vyc29yLCAibm9kZUlEcyIsDQoJCQkJCQl1
dGlsLmNvbnZlcnRPYmplY3RUb1N0cmluZ0FycmF5KG5vZGVJRHMpKTsNCgkJCQlJRGF0YVV0aWwu
cHV0KHBpcGVDdXJzb3IsICJjb250ZW50RGVmcyIsDQoJCQkJCQl1dGlsLmNvbnZlcnRPYmplY3RU
b1N0cmluZ0FycmF5KGNvbnRlbnREZWZzKSk7DQoJCQkJSURhdGFVdGlsLnB1dChwaXBlQ3Vyc29y
LCAiZGVzY3JpcHRpb24iLA0KCQkJCQkJdXRpbC5jb252ZXJ0T2JqZWN0VG9TdHJpbmdBcnJheShk
ZXNjcmlwdGlvbikpOw0KCQkJCVN0cmluZyBjc3BGaWx0ZXJOYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyhwaXBlQ3Vyc29yLA0KCQkJCQkJImNzcEZpbHRlckZyaWVuZGx5TmFtZSIpOw0KCQkJCUlE
YXRhVXRpbA0KCQkJCQkJLnB1dChwaXBlQ3Vyc29yLCAiZnJpZW5kbHlOYW1lIiwgY3NwRmlsdGVy
TmFtZSk7DQoJCQkJcGlwZUN1cnNvci5kZXN0cm95KCk7DQoJCQkJKChFQ29udGVudFJlcG9zaXRv
cnkpIHJlcG8pLnN0b3JlRG9jRmlsdGVyKHBpcGVsaW5lKTsNCgkJCX0NCgkJCWlmIChyZXBvID09
IG51bGwpIHsNCgkJCQlzdGF0dXMgPSAiRmFpbGVkOiB0byBjcmVhdGUgY29ubmVjdGlvbiB0byBD
U1Agc2VydmVyLiBTZXJ2ZXIgaXMgZG93biBvciBpbnZhbGlkIGNvbm5lY3Rpb24gZGV0YWlscy4i
Ow0KCQkJfQ0KCQkJSURhdGFVdGlsLnB1dChwaXBlQ3Vyc29yLCAic3RhdHVzIiwgc3RhdHVzKTsN
CgkJfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCgkJCXRocm93IGU7DQoJCX0gZmluYWxseSB7DQoJ
CQlpZiAocGlwZUN1cnNvciAhPSBudWxsKQ0KCQkJCXBpcGVDdXJzb3IuZGVzdHJveSgpOw0KCQl9
DQoJfQ0KfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCglTdHJpbmdXcml0ZXIgcmVzdWx0ID0gbmV3
IFN0cmluZ1dyaXRlcigpOw0KCVByaW50V3JpdGVyIHByaW50V3JpdGVyID0gbmV3IFByaW50V3Jp
dGVyKHJlc3VsdCk7DQoJZS5wcmludFN0YWNrVHJhY2UocHJpbnRXcml0ZXIpOw0KCXV0aWwubG9n
Z2VyLmVycm9yKHJlc3VsdC50b1N0cmluZygpKTsNCgllLnByaW50U3RhY2tUcmFjZSgpOw0KfQ0K
</value>
</Values>
