/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wm_swiftnet_client_WmSWIFTNetClientJNI */

#ifndef _Included_com_wm_swiftnet_client_WmSWIFTNetClientJNI
#define _Included_com_wm_swiftnet_client_WmSWIFTNetClientJNI
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: inited */
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_SUCCESS
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_SUCCESS 0L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_INTERNAL
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_INTERNAL 1L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_IS_CLIENT
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_IS_CLIENT 2L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_CALLED_TWICE
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_CALLED_TWICE 3L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_NO_CALLBACKS
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_NO_CALLBACKS 4L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_BAD_DLL
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_BAD_DLL 5L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_ACCESS_DLL
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_ACCESS_DLL 6L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_ACCESS_CFG
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_ACCESS_CFG 7L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_NO_VERSION
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_NO_VERSION 8L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_FORMAT_CFG
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_FORMAT_CFG 9L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_FORMAT_ARG
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_FORMAT_ARG 10L
#undef com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_PREVIOUS_ERROR
#define com_wm_swiftnet_client_WmSWIFTNetClientJNI_SWLIB_E_PREVIOUS_ERROR 11L
/*
 * Class:     com_wm_swiftnet_client_WmSWIFTNetClientJNI
 * Method:    WmSwArguments
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_wm_swiftnet_client_WmSWIFTNetClientJNI_WmSwArguments
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     com_wm_swiftnet_client_WmSWIFTNetClientJNI
 * Method:    WmSwCall
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_wm_swiftnet_client_WmSWIFTNetClientJNI_WmSwCall
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
