REM -----------OBJECT CREATION--------------------
REM -- FOR ORACLE APPLICATIONS ADAPTER TRANSACTION
REM -- CONFIGURATION DATA

REM Table for holding the transaction names for each OA release

CREATE TABLE OA_TRANSACTION(
 OATXN_ID NUMBER(5),
 OATXN_RELEASE    VARCHAR2(24),		--OA Release (10SC, etc)
 OATXN_TXN_NAME  VARCHAR2(200),
 OATXN_TXN_TYPE  VARCHAR2(12),		-- 'IN' \ 'OUT'
 OATXN_ERRACK_SQL VARCHAR2(4000) 	--ErrSql for ISToOA and Ack SQL for OAtoIS 
)
/

ALTER TABLE OA_TRANSACTION
       ADD CONSTRAINT OATXN_PKX PRIMARY KEY (OATXN_ID)
/

CREATE UNIQUE INDEX OATXN_AKX ON OA_TRANSACTION
	(OATXN_RELEASE, OATXN_TXN_NAME)
/

CREATE SEQUENCE OATXN_ID_SEQ START WITH 1000 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER OATXN_TBI BEFORE INSERT
  ON OA_TRANSACTION REFERENCING NEW AS NEW
  FOR EACH ROW BEGIN
    SELECT OATXN_ID_SEQ.nextval INTO :NEW.OATXN_ID FROM DUAL;
  END;
/

--FOR INBOUND (OA TO IS) TRANSACTIONS
CREATE TABLE OA_TRANSACTION_OUT(
 OATXN_ID NUMBER(5),
 OATXNOUT_SQL_SEQ	NUMBER(4),
 OATXNOUT_SQL_REF	NUMBER(3), --Reference to parent sequence
 OATXNOUT_SQL_ALIAS 	VARCHAR2(200),
 OATXNOUT_SQL_RELATION 	VARCHAR2(4000),
 OATXNOUT_SQL_OUT 	CLOB
)
/

ALTER TABLE OA_TRANSACTION_OUT
ADD CONSTRAINT OATXNOUT_PKX PRIMARY KEY (OATXN_ID,OATXNOUT_SQL_SEQ)
/

--FOR OUT BOUND (OA TO IS) TRANSACTIONS
CREATE TABLE OA_TRANSACTION_IN(
 OATXN_ID NUMBER(5),
 OATXNIN_TABLE_SEQ      NUMBER(3),
 OATXNIN_TABLE_NAME      VARCHAR2(200),
 OATXNIN_REQUIRED_FLAG    VARCHAR2(20)
)
/

ALTER TABLE OA_TRANSACTION_IN
       ADD CONSTRAINT OATXNIN_PKX PRIMARY KEY (OATXN_ID, OATXNIN_TABLE_SEQ)
/

