REM --MIGRATION SCRIPT FOR ORACLE APPLICATIONS ADAPTER 
REM --TRANSACTION CONFIGURATION DATA 
REM --FROM ORA_6-0_Fix7 TO ORA_6-0_Fix8

ALTER TABLE OA_TRANSACTION_OUT
DROP CONSTRAINT OATXNOUT_PKX 
/

ALTER TABLE OA_TRANSACTION_OUT
ADD OATXNOUT_SQL_SEQ	NUMBER(4) DEFAULT 1  --SQL ALIAS SEQUENCE
/

ALTER TABLE OA_TRANSACTION_OUT
ADD OATXNOUT_SQL_REF	NUMBER(3) DEFAULT 0  --SEQUENCE OF PARENT SQL ALIAS
/

UPDATE OA_TRANSACTION_OUT
SET OATXNOUT_SQL_SEQ = OATXNOUT_SQL_LEVEL + 1    --COPYING THE EXISTING PK, SEQ STARTS WITH 1
/

UPDATE OA_TRANSACTION_OUT
SET OATXNOUT_SQL_REF = OATXNOUT_SQL_LEVEL  
WHERE OATXNOUT_SQL_LEVEL > 0		     --SETTING PARENT REFERENCE FOR CHILD NODES
/

ALTER TABLE OA_TRANSACTION_OUT
DROP COLUMN OATXNOUT_SQL_LEVEL
/

ALTER TABLE OA_TRANSACTION_OUT
ADD CONSTRAINT OATXNOUT_PKX PRIMARY KEY (OATXN_ID,OATXNOUT_SQL_SEQ)
/
