<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createListener</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required friendlyName</value>
    <value>[i] field:0:required cspListenerFriendlyName</value>
    <value>[i] field:0:required eventType</value>
    <value>[i] field:0:required nodeIDs</value>
    <value>[i] field:0:optional searchFilter</value>
    <value>[i] field:0:required isName</value>
    <value>[i] field:0:optional description</value>
    <value>[o] field:0:required status</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5IHsNCglpZiAocGlwZWxpbmUgIT0gbnVsbCkgew0KCQlJRGF0YUN1cnNvciBwaXBlQ3Vyc29y
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJCUlEYXRhIGNyZWF0ZUxpc3RlbmVyID0gSURhdGFG
YWN0b3J5LmNyZWF0ZSgpOw0KCQlTdHJpbmcgY3NwU2VydmVyRnJpZW5kbHlOYW1lID0gSURhdGFV
dGlsLmdldFN0cmluZyhwaXBlQ3Vyc29yLA0KCQkJCSJmcmllbmRseU5hbWUiKTsNCgkJU3RyaW5n
IGNzcEZyaWVuZGx5TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcocGlwZUN1cnNvciwNCgkJCQki
Y3NwTGlzdGVuZXJGcmllbmRseU5hbWUiKTsNCgkJT2JqZWN0IGNydWRWYWx1ZXMgPSBJRGF0YVV0
aWwuZ2V0KHBpcGVDdXJzb3IsICJldmVudFR5cGUiKTsNCgkJT2JqZWN0IGNtcFN0YXJ0Tm9kZXMg
PSBJRGF0YVV0aWwuZ2V0KHBpcGVDdXJzb3IsICJub2RlSURzIik7DQoJCVN0cmluZyBzZWFyY2hG
aWx0ZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKHBpcGVDdXJzb3IsDQoJCQkJInNlYXJjaEZpbHRl
ciIpOw0KCQlPYmplY3QgaXNOYW1lID0gSURhdGFVdGlsLmdldChwaXBlQ3Vyc29yLCAiaXNOYW1l
Iik7DQoJCU9iamVjdCBkZXNjcmlwdGlvbiA9IElEYXRhVXRpbC5nZXQocGlwZUN1cnNvciwgImRl
c2NyaXB0aW9uIik7DQoJCVN0cmluZyBoaWRkZW5VcGRhdGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KHBpcGVDdXJzb3IsDQoJCQkJImhpZGRlblVwZGF0ZSIpOw0KCQlpZiAoIlllcyIuZXF1YWxzKGhp
ZGRlblVwZGF0ZSkpIHsNCgkJCWNydWRWYWx1ZXMgPSAiQ1JFQVRFIjsNCgkJfQ0KCQlwaXBlQ3Vy
c29yLmRlc3Ryb3koKTsNCg0KCQkvLyBNYXA8U3RyaW5nLCBDUk1hbmFnZXI+IHJlcG9zID0gTGlz
dGVuZXJNYW5hZ2VyLmdldFJlcG9JbmRleCgpOw0KCQlJRGF0YUN1cnNvciBsaXN0ZW5lckN1cnNv
ciA9IGNyZWF0ZUxpc3RlbmVyLmdldEN1cnNvcigpOw0KCQlJRGF0YVV0aWwucHV0KGxpc3RlbmVy
Q3Vyc29yLCAibm9kZUlEcyIsDQoJCQkJdXRpbC5jb252ZXJ0T2JqZWN0VG9TdHJpbmdBcnJheShj
bXBTdGFydE5vZGVzKSk7DQoJCUlEYXRhVXRpbC5wdXQobGlzdGVuZXJDdXJzb3IsICJmcmllbmRs
eU5hbWUiLCBjc3BGcmllbmRseU5hbWUpOw0KCQlJRGF0YVV0aWwucHV0KGxpc3RlbmVyQ3Vyc29y
LCAiaXNOYW1lIiwNCgkJCQl1dGlsLmNvbnZlcnRPYmplY3RUb1N0cmluZ0FycmF5KGlzTmFtZSkp
Ow0KCQlJRGF0YVV0aWwucHV0KGxpc3RlbmVyQ3Vyc29yLCAicGFja2FnZU5hbWUiLA0KCQkJCXV0
aWwuY29udmVydE9iamVjdFRvU3RyaW5nQXJyYXkoIndtLmVjb250ZW50LmVjb250ZW50IikpOw0K
CQlJRGF0YVV0aWwucHV0KGxpc3RlbmVyQ3Vyc29yLCAic2VydmljZU5hbWUiLA0KCQkJCXV0aWwu
Y29udmVydE9iamVjdFRvU3RyaW5nQXJyYXkoInB1Ymxpc2hDU1BFRm9ybURvYyIpKTsNCgkJSURh
dGFVdGlsLnB1dChsaXN0ZW5lckN1cnNvciwgImV2ZW50VHlwZSIsDQoJCQkJdXRpbC5jb252ZXJ0
T2JqZWN0VG9TdHJpbmdBcnJheShjcnVkVmFsdWVzKSk7DQoJCUlEYXRhVXRpbC5wdXQobGlzdGVu
ZXJDdXJzb3IsICJlbmFibGUiLA0KCQkJCXV0aWwuY29udmVydE9iamVjdFRvU3RyaW5nQXJyYXko
Ik5vIikpOw0KCQlJRGF0YVV0aWwucHV0KGxpc3RlbmVyQ3Vyc29yLCAiZGVzY3JpcHRpb24iLA0K
CQkJCXV0aWwuY29udmVydE9iamVjdFRvU3RyaW5nQXJyYXkoZGVzY3JpcHRpb24pKTsNCgkJSURh
dGFVdGlsLnB1dChsaXN0ZW5lckN1cnNvciwgImZpbHRlciIsIHNlYXJjaEZpbHRlcik7DQoJCWxp
c3RlbmVyQ3Vyc29yLmRlc3Ryb3koKTsNCgkJRUNvbnRlbnRSZXBvc2l0b3J5IHJlcG8gPSB1dGls
LmdldFJlcG8oY3NwU2VydmVyRnJpZW5kbHlOYW1lKTsNCgkJU3RyaW5nIHN0YXR1cyA9ICJTdWNj
ZXNzIjsNCgkJaWYgKHJlcG8gIT0gbnVsbCkgew0KCQkJaWYgKCFyZXBvLmlzTGl2ZSgpKSB7DQoJ
CQkJcmVwby5nZXRSZXBvKCk7DQoJCQl9DQoJCQlyZXBvLnN0b3JlTGlzdGVuZXIoY3JlYXRlTGlz
dGVuZXIpOw0KCQl9IGVsc2Ugew0KCQkJc3RhdHVzID0gIkZhaWxlZDogdG8gY3JlYXRlIGNvbm5l
Y3Rpb24gdG8gQ1NQIHNlcnZlci4gU2VydmVyIGlzIGRvd24gb3IgaW52YWxpZCBjb25uZWN0aW9u
IGRldGFpbHMuIjsNCgkJfQ0KCQlJRGF0YVV0aWwucHV0KHBpcGVDdXJzb3IsICJzdGF0dXMiLCBz
dGF0dXMpOw0KCX0NCn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7DQoJU3RyaW5nV3JpdGVyIHJlc3Vs
dCA9IG5ldyBTdHJpbmdXcml0ZXIoKTsNCglQcmludFdyaXRlciBwcmludFdyaXRlciA9IG5ldyBQ
cmludFdyaXRlcihyZXN1bHQpOw0KCWUucHJpbnRTdGFja1RyYWNlKHByaW50V3JpdGVyKTsNCgl1
dGlsLmxvZ2dlci5lcnJvcihyZXN1bHQudG9TdHJpbmcoKSk7DQoJZS5wcmludFN0YWNrVHJhY2Uo
KTsNCn0NCg==</value>
</Values>
