-- -----------OBJECT CREATION--------------------
-- FOR ORACLE APPLICATIONS ADAPTER TRANSACTION
-- CONFIGURATION DATA

-- Table for holding the transaction names for each OA release

CREATE TABLE OA_TRANSACTION(
 OATXN_ID INTEGER NOT NULL,
 OATXN_RELEASE    VARCHAR(24),		--OA Release (10SC, etc)
 OATXN_TXN_NAME  VARCHAR(200),
 OATXN_TXN_TYPE  VARCHAR(12),		-- 'IN' \ 'OUT'
 OATXN_ERRACK_SQL VARCHAR(4000) 	--ErrSql for ISToOA and Ack SQL for OAtoIS 
)
;

ALTER TABLE OA_TRANSACTION
       ADD PRIMARY KEY (OATXN_ID)
;

CREATE UNIQUE INDEX OATXN_AKX ON OA_TRANSACTION
	(OATXN_RELEASE, OATXN_TXN_NAME)
;

CREATE SEQUENCE OATXN_ID_SEQ START WITH 1000 INCREMENT BY 1;

CREATE TRIGGER OATXN_TBI 
BEFORE INSERT ON OA_TRANSACTION REFERENCING NEW AS NEW 
FOR EACH ROW MODE DB2SQL  
SET NEW.OATXN_ID=NEXT VALUE FOR OATXN_ID_SEQ;

--FOR INBOUND (OA TO IS) TRANSACTIONS
CREATE TABLE OA_TRANSACTION_OUT(
 OATXN_ID INTEGER NOT NULL,
 OATXNOUT_SQL_SEQ	SMALLINT NOT NULL,
 OATXNOUT_SQL_REF	SMALLINT, --Reference to parent sequence
 OATXNOUT_SQL_ALIAS 	VARCHAR(200),
 OATXNOUT_SQL_RELATION 	VARCHAR(4000),
 OATXNOUT_SQL_OUT 	CLOB
)
;

ALTER TABLE OA_TRANSACTION_OUT
ADD PRIMARY KEY (OATXN_ID,OATXNOUT_SQL_SEQ)
;

--FOR OUT BOUND (OA TO IS) TRANSACTIONS
CREATE TABLE OA_TRANSACTION_IN(
 OATXN_ID INTEGER NOT NULL,
 OATXNIN_TABLE_SEQ      SMALLINT NOT NULL,
 OATXNIN_TABLE_NAME      VARCHAR(200),
 OATXNIN_REQUIRED_FLAG    VARCHAR(20)
)
;

ALTER TABLE OA_TRANSACTION_IN
       ADD PRIMARY KEY (OATXN_ID, OATXNIN_TABLE_SEQ)
;

