-----------OBJECT CREATION--------------------
-- FOR ORACLE APPLICATIONS ADAPTER TRANSACTION
-- CONFIGURATION DATA

-- Table for holding the transaction names for each OA release

CREATE TABLE OA_TRANSACTION(
 OATXN_ID int NOT NULL IDENTITY (1000,1),
 OATXN_RELEASE    nvarchar(24),		--OA Release (10SC, etc)
 OATXN_TXN_NAME  nvarchar(200),
 OATXN_TXN_TYPE  nvarchar(12),		-- 'IN' \ 'OUT'
 OATXN_ERRACK_SQL nvarchar(4000) 	--ErrSql for ISToOA and Ack SQL for OAtoIS 
)
go

ALTER TABLE OA_TRANSACTION
       ADD CONSTRAINT OATXN_PKX PRIMARY KEY (OATXN_ID)
go

CREATE UNIQUE INDEX OATXN_AKX ON OA_TRANSACTION
	(OATXN_RELEASE, OATXN_TXN_NAME)
go



--FOR INBOUND (OA TO IS) TRANSACTIONS
CREATE TABLE OA_TRANSACTION_OUT(
 OATXN_ID int NOT NULL,
 OATXNOUT_SQL_SEQ	int NOT NULL,
 OATXNOUT_SQL_REF	int, --Reference to parent sequence
 OATXNOUT_SQL_ALIAS 	nvarchar(200),
 OATXNOUT_SQL_RELATION 	nvarchar(4000),
 OATXNOUT_SQL_OUT 	nvarchar(max)
)
go

ALTER TABLE OA_TRANSACTION_OUT
ADD CONSTRAINT OATXNOUT_PKX PRIMARY KEY (OATXN_ID,OATXNOUT_SQL_SEQ)
go

--FOR OUT BOUND (OA TO IS) TRANSACTIONS
CREATE TABLE OA_TRANSACTION_IN(
 OATXN_ID smallint NOT NULL,
 OATXNIN_TABLE_SEQ      smallint NOT NULL,
 OATXNIN_TABLE_NAME      nvarchar(200),
 OATXNIN_REQUIRED_FLAG    nvarchar(20)
)
go

ALTER TABLE OA_TRANSACTION_IN
       ADD CONSTRAINT OATXNIN_PKX PRIMARY KEY (OATXN_ID, OATXNIN_TABLE_SEQ)
go

